### ISSUE TITLE
NameError: uninitialized constant PDF [solved]

### ISSUE THREAD

**Issue by amisukanta** [gdelugre/origami#1]
I am trying to use origami to add digital signature and encryption but when I am trying to use this gem, getting.

```
[1] pry(main)> require 'origami'
=> true
[2] pry(main)> pdf = PDF.read "something.pdf"
NameError: uninitialized constant PDF

```

I found the solution. I need to call the constructor

```
Origami::PDF.read('something.pdf')

```

**Comment by gdelugre** [comment]
I realize the examples in the README do not include the Origami namespace.

Thank you for pointing that out.
