### ISSUE TITLE
Error: undefined method `read' for PDF:Module

### ISSUE THREAD

**Issue by s2t2** [gdelugre/origami#12]
I'm trying to use this gem to parse a PDF file that exists on my local file system. When I follow the instructions, this gem doesn't work. Please advise!

```` rb
require "origami"
include Origami

local_file = File.join(File.expand_path("../../tmp", __FILE__), "my_report.pdf")

pdf = PDF.read(local_file)

#> NoMethodError: undefined method `read' for PDF:Module
````

Versions:

  + origami 2.0.2
  + ruby 2.2.3p173

**Comment by gdelugre** [comment]
I am unable to reproduce this problem with the ``2.0.2`` gem on any versions of Ruby.
Are you sure you don't have another library defining its own version of a ``PDF`` class or module ?

Is the problem present if you use explicitly call ```Origami::PDF.read(local_file)``` ?
