### ISSUE TITLE
--no-color option not working

### ISSUE THREAD

**Issue by parosterbergmedina** [gdelugre/origami#2]
I cannot get the '--no-color' option to work properly. The first two output lines are displayed without ESC codes but the following output lines are not. I am running ruby-colorize 0.8.1-2 and 2.0.0-1, both installed from Arch and Archstrike repositories.

Please let me know if you can reproduce and if there is any easy fix to this issue.

**Comment by andusvan** [comment]
This is a regression to version 1.2.7. 
There the --no-color option works mostly, but fails if the program outputs an error message.

**Comment by gdelugre** [comment]
Indeed there was a line of code conflicting with the colorization option.

I think it should be fixed now.

**Comment by andusvan** [comment]
It's fixed for me...

**Comment by gdelugre** [comment]
The gem version has been updated to 2.0.1 with the latest fixes.
