### ISSUE TITLE
'encryption' example: created document doesn't render properly

### ISSUE THREAD

**Issue by salpha2004** [gdelugre/origami#23]
Origami v2.0.3

$ ruby examples/encryption/encryption.rb
PDF file saved as encryption.pdf.

When I open the file with Adobe Reader 9.0 (yeah it's pretty old!), I get the following:
![image](https://user-images.githubusercontent.com/1822668/30433863-e604b1d0-9965-11e7-9eea-a4209bd87e1b.png)

But even Adobe Reader DC doesn't render it properly because even though it doesn't throw an error, it doesn't show the content either (_Encrypted document sample_).
![image](https://user-images.githubusercontent.com/1822668/30433949-2a99d82a-9966-11e7-9f64-84b3fdcb73bb.png)

**Comment by gdelugre** [comment]
There was indeed a regression introduced in the library. The latest version on the repository has got fixed, I will push a new version soon.

**Comment by gdelugre** [comment]
Fixed in 2.0.4
