### ISSUE TITLE
Is it possible to support SHA256 and not SHA1 for certificates siging

### ISSUE THREAD

**Issue by elico** [gdelugre/origami#24]
I have seen that from line:
https://github.com/gdelugre/origami/blob/8ba8d707c6d2d63041a1fe323facb7925e3823e2/lib/origami/signature.rb#L202

That the it's like always the signature digest is used with SHA1 while PDF supports SHA256 and SHA512.
Is there any way to add support for these?

**Comment by gdelugre** [comment]
When the PKCS7 signature is detached, the digest used is selected by OpenSSL automatically. SHA256 should be selected as the default digest unless you are running a quite old version of OpenSSL.

Which version of OpenSSL are you using? From what I'm seeing, they switched to SHA2 three years ago: https://github.com/openssl/openssl/commit/44e0c2bae4bfd87d770480902618dbccde84fd81#diff-dbf726cfa20d03251a1eb72683972640

**Comment by elico** [comment]
@gdelugre 
```
$ yum info openssl
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.joinweb.co.il
 * elrepo: lon.mirror.rackspace.com
 * epel: epel.mirrors.ovh.net
 * ius: lon.mirror.rackspace.com
 * updates: centos.joinweb.co.il
Installed Packages
Name        : openssl
Arch        : x86_64
Epoch       : 1
Version     : 1.0.2k
Release     : 8.el7
Size        : 814 k
Repo        : installed
From repo   : base
Summary     : Utilities from the general purpose cryptography library with TLS implementation
URL         : http://www.openssl.org/
License     : OpenSSL
Description : The OpenSSL toolkit provides support for secure communications between
            : machines. OpenSSL includes a certificate management tool and shared
            : libraries which provide various cryptographic algorithms and
            : protocols.
```
I will try to run it on the latest Debian and Ubuntu but from I have seen in the code there are two things which we are looking at.
The first is the certificate SHA signature which is SHA256 and.. the document signature.
The origami code uses almost explicitly(to my eyes) SHA1 and MD5 as the document DIGEST signature not the certificate one.

This is the code I am using as a demo of signing:
https://gist.github.com/elico/d203aaf4667d592cb45b669d878ffe99

I am creating a new signature signed with SHA256 and then sign with it the PDF.
In the PDF properties I have only SHA1 and MD5 digest but the certificate has SHA256 signature.
Is it right? Maybe I'm doing something wrong?

Thanks!

**Comment by gdelugre** [comment]
Where do you see a SHA1 and MD5 digest? There's no chance that MD5 is used in the signature.

I have actually tested your code with an installation of OpenSSL ``1.0.1t`` (on an old version of Debian) and ``1.1.0f``. Both generate a SHA256 signature.

This can be checked directly by looking at the generated p7 structure:
```
    0:d=0  hl=4 l=1799 cons: SEQUENCE
    4:d=1  hl=2 l=   9 prim: OBJECT            :pkcs7-signedData
   15:d=1  hl=4 l=1784 cons: cont [ 0 ]
   19:d=2  hl=4 l=1780 cons: SEQUENCE
   23:d=3  hl=2 l=   1 prim: INTEGER           :01
   26:d=3  hl=2 l=  15 cons: SET
   28:d=4  hl=2 l=  13 cons: SEQUENCE
   30:d=5  hl=2 l=   9 prim: OBJECT            :sha256
   41:d=5  hl=2 l=   0 prim: NULL
   43:d=3  hl=2 l=  11 cons: SEQUENCE
   45:d=4  hl=2 l=   9 prim: OBJECT            :pkcs7-data
   56:d=3  hl=4 l=1051 cons: cont [ 0 ]
   60:d=4  hl=4 l=1047 cons: SEQUENCE
...
 1282:d=5  hl=2 l=  13 cons: SEQUENCE
 1284:d=6  hl=2 l=   9 prim: OBJECT            :sha256
 1295:d=6  hl=2 l=   0 prim: NULL
 1297:d=5  hl=3 l= 228 cons: cont [ 0 ]
 1300:d=6  hl=2 l=  24 cons: SEQUENCE
 1302:d=7  hl=2 l=   9 prim: OBJECT            :contentType
 1313:d=7  hl=2 l=  11 cons: SET
 1315:d=8  hl=2 l=   9 prim: OBJECT            :pkcs7-data
 1326:d=6  hl=2 l=  28 cons: SEQUENCE
 1328:d=7  hl=2 l=   9 prim: OBJECT            :signingTime
 1339:d=7  hl=2 l=  15 cons: SET
 1341:d=8  hl=2 l=  13 prim: UTCTIME           :171002110651Z
 1356:d=6  hl=2 l=  47 cons: SEQUENCE
 1358:d=7  hl=2 l=   9 prim: OBJECT            :messageDigest
 1369:d=7  hl=2 l=  34 cons: SET
 1371:d=8  hl=2 l=  32 prim: OCTET STRING      [HEX DUMP]:E305E9D33A9B67C135900EB1E2C1321C49DEEF0E6568B00B9A0667F6B7DC216C

```

 The signature algorithm used in the PKCS7 object is unrelated to the one used to sign your certificates.

**Comment by gdelugre** [comment]
By the way, you can inspect the used digest algorithm in Adobe Reader by clicking on the signature, displaying its properties, then going to "Advanced properties". This will provide you with the information that SHA256 is indeed the digest used.

"*The origami code uses almost explicitly(to my eyes) SHA1 and MD5 as the document DIGEST signature not the certificate one.*"

It never uses MD5. It will use SHA1 explicitely only if you pass the argument ``adbe.pkcs7.sha1`` to the ``sign`` method. Otherwise the default ``adbe.pkcs7.detached`` will rely on the default message digest algorithm of OpenSSL which is SHA256.

**Comment by elico** [comment]
@gdelugre Then I am probably understanding what Adobe spaghetti details means.
Now that I look at it I think it's a specific digest sum done by Adobe on the specific part which is singed by the signature:
part1: https://snag.gy/0vACZD.jpg
part2: https://snag.gy/MRSlk0.jpg

**Comment by gdelugre** [comment]
These are just the fingerprints of the certificate you're using.

They are not part of the certificate nor the signature, they are simply digests of the DER-encoded certificate. It is only meant to be informative.

You can compute the same values like this:
```ruby
Digest::MD5.hexdigest OpenSSL::PKCS7.new(PDF.read("signed.pdf").signature.Contents).certificates.first.to_der
```

**Comment by gdelugre** [comment]
You would also obtain the same value with:
```
$ openssl x509 -fingerprint -in test.crt
```
