### ISSUE TITLE
Missing option to deactivate password prompt

### ISSUE THREAD

**Issue by andusvan** [gdelugre/origami#3]
To use "ipcop" in a script it's necessary to disable the password prompt. Otherwise the script will stop and cannot continue until a user presses a key.
Please add an option to disable the password prompt.

**Comment by gdelugre** [comment]
It should already exists.

There are two possible options that can be passed to ``PDF.read``.

- ``password`` : the default password being tried when reading an encrypted document (default to an empty string).
- ``prompt_password`` : a procedure to call if the password is incorrect. By default it prompts for the password on the standard input.

https://github.com/gdelugre/origami/blob/master/lib/origami/parsers/pdf.rb#L31

To disable the password prompt, the simplest way should be to override the ``prompt_password`` option with a lambda returning "".

**Comment by andusvan** [comment]
OK, but I'm using the "pdfcop" tool and how do I specify it there?

It would be nice if the tool would just report "rejected" if the PDF file is
encrypted and to config option "allowEncryption" is set to false (as in the paranoid policy)
without asking any password.

**Comment by gdelugre** [comment]
I have modified the behavior of ``pdfcop`` in two ways:

1. No decryption will be attempted (and no password asked) if ``allowEncryption`` is disabled for the chosen policy

2. A command-line switch ``--password`` allows to pass the password for script processing

Does that look okay to you?

**Comment by andusvan** [comment]
Yes, this will work!
Thanks for the quick fixes!
