### ISSUE TITLE
Cannot verify pdf signature of subfilter "adbe.x509.rsa_sha1"

### ISSUE THREAD

**Issue by sumanthmadishetty** [gdelugre/origami#46]
Hi

When I try to verify a pdf signature of type "adbe.x509.rsa_sha1" it is throwing an error and when i try to verify it with PKCS7 It says that the argument should be of type X509 . how can i verify the signature of PDF in such a case

**Comment by gdelugre** [comment]
From what I recall, I struggled to implement adbe.x509.rsa_sha1 because I wasn't able to generate a valid document that would be verified by Adobe Reader.

Do you have an example of such a document? I could use it for implementing the feature.

**Comment by THausherr** [comment]
This answer
https://stackoverflow.com/a/52861045/535646
shows how to verify with BouncyCastle and links to this file that has such a signature
https://issues.apache.org/jira/secure/attachment/12701059/in.pdf

**Comment by gdelugre** [comment]
The support has been added to master at https://github.com/gdelugre/origami/commit/c4e5d663f3f45ab99dd8f226419098deb7c3116c
