### ISSUE TITLE
Option to serve file without saving to disk?

### ISSUE THREAD

**Issue by bassambarham** [gdelugre/origami#55]
Hi

Is there a method to server the file using send_data without saving the file to desk?

Thanks

**Comment by gdelugre** [comment]
The ``save`` method accepts either a file path, or an object responding to the ``write`` method (like an ``IO`` object).

So, in order to not write the result to disk, you could do this:
```ruby
# Save the PDF into a String
pdf, io = Origami::PDF.new, StringIO.new
pdf.save(io)
str = io.string

# Or 
socket = TCPSocket.new(host, port)
pdf.save(socket)
```

Does this answer your question?

**Comment by bassambarham** [comment]
Yes it does.

Thanks a lot for your help.
