### ISSUE TITLE
Can the version of colorize dependency be upgraded?

### ISSUE THREAD

**Issue by Laykou** [gdelugre/origami#88]
Right now it depends on `colorize '~> 0.8'`

Can this be lifted to at least `~> 1.1.0` or later version?

I'm having conflicts with other gems, like `langchainrb`

**Comment by ekzobrain** [comment]
Hi. Origami is currently unsupported, it's author does not answer and does not fix anything. I switched to https://github.com/gettalong/hexapdf - it is a much more powerfull library.

**Comment by Laykou** [comment]
Thank you. I found out this updated version of Origami too: https://github.com/mindee/origamindee
